"""Wallets worth mirroring, and the measurement that earned them the place.

GENERATED by ``tools/wallet_research/taker_screen.py`` + a drift check, over the
last 30 days of resolved BTC/ETH/XRP HOURLY and BTC/ETH/SOL/XRP 15-MINUTE
Up-or-Down markets (7.2M and 10.8M fills respectively). Re-run both
before trusting this list again; the measurements below are a snapshot.

**Why these are not the highest-profit wallets.** Ranking by profit finds market
makers. Their edge IS the spread, they sit on the other side of the trade from a
follower, and copying one converts their profit into your cost. `0x9d57c42e` is
the clearest case: +$32,064 while buying BOTH outcomes in 3,054 of its 3,151
markets. There is no side to follow, and a copier crossing to mirror it nets
-$39,662.

So every wallet here was classified fill-by-fill against the ``takerOnly=true``
feed and ranked on its TAKER fills alone — the flow a follower who crosses the
spread can reproduce. ``taker_share`` is measured by NOTIONAL, not fill count: a
wallet can rest most of its tickets and still push most of its money across.

**Why they are small.** Ordinary accounts staking $1-$148 a market, not whales.
Capacity is not a constraint for a follower at these sizes.

**Drift is checked BEFORE registration.** An earlier registry lost 7 of 9 targets
to drift — wallets screened on Up-or-Down had moved to strike markets, weather
and college football, and a measured edge does not transfer to a market the
wallet was never measured on. Every wallet below had >=60% of its last-7-day flow
still on 15m/1h Up-or-Down, and the dashboard tracks that ratio live.

**Read the t-stats honestly.** Most sit near 1. Individually that is weak; the
response is to follow many of them and let real paper outcomes settle it, not to
bet the list on any one name.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Target:
    """A wallet to mirror, with the evidence that selected it."""

    address: str
    label: str
    taker_share: float
    """Fraction of its NOTIONAL that crossed the spread, measured against the
    takerOnly feed. Below ~0.55 the wallet is quoting and cannot be followed."""
    edge_cents: float
    """Net edge per share on its TAKER fills only, after the taker fee."""
    t_stat: float
    markets: int
    avg_stake_usd: float
    avg_entry: float
    in_scope: float
    """Fraction of last-7-day flow still on 15m/1h Up-or-Down markets."""
    fills_per_day: float
    assets: str = "btc, eth 15m+1h"
    cadence: str = "intraday"
    note: str = ""

    @property
    def key(self) -> str:
        return self.address.lower()

    @property
    def edge_left_30min(self) -> float:
        """Shown by the panel; intraday targets are never copied 30 min late."""
        return self.edge_cents

    @property
    def runway_p10_min(self) -> float:
        return 0.0


TARGETS: dict[str, Target] = {
    t.key: t
    for t in (
        Target(
            address="0x8d773331e432935c7cb6c24ded4c5e1a8f35ee05",
            label="t-8d77",
            taker_share=0.92, edge_cents=38.25, t_stat=0.76,
            markets=470, avg_stake_usd=1, avg_entry=0.430,
            in_scope=1.00, fills_per_day=21.7,
            assets="btc, eth 1h",
            note="mid-price taker with a 470-market record - the shape the screen was asked for.",
        ),
        Target(
            address="0x7d5c80c3cb81911c9bcce79e99ac116efaf34cfd",
            label="t-7d5c",
            taker_share=0.67, edge_cents=32.42, t_stat=0.43,
            markets=13, avg_stake_usd=21, avg_entry=0.503,
            in_scope=1.00, fills_per_day=2.0,
            assets="btc, eth 1h",
        ),
        Target(
            address="0x14cabd26ade5315e79da8f9efb085ace0028da18",
            label="t-14ca",
            taker_share=0.87, edge_cents=31.70, t_stat=0.17,
            markets=75, avg_stake_usd=2, avg_entry=0.658,
            in_scope=1.00, fills_per_day=14.0,
            assets="btc, eth 1h",
        ),
        Target(
            address="0x2c175b735a264f2e2c53244c2b098baeefeab888",
            label="t-2c17",
            taker_share=1.00, edge_cents=22.47, t_stat=1.16,
            markets=32, avg_stake_usd=25, avg_entry=0.895,
            in_scope=1.00, fills_per_day=19.7,
            assets="btc, eth 1h",
        ),
        Target(
            address="0x91078d02b6db710baa37c028519b2d9592b9b6e0",
            label="t-9107",
            taker_share=0.86, edge_cents=20.90, t_stat=0.69,
            markets=107, avg_stake_usd=148, avg_entry=0.817,
            in_scope=1.00, fills_per_day=5.0,
            assets="btc, eth 1h",
        ),
        Target(
            address="0x6b1b435a547d245675cbbf268a2b9f4ce8970d3c",
            label="t-6b1b",
            taker_share=0.60, edge_cents=19.66, t_stat=2.95,
            markets=20, avg_stake_usd=44, avg_entry=0.507,
            in_scope=1.00, fills_per_day=25.4,
            assets="btc, eth 1h",
        ),
        Target(
            address="0x7cbc58d87704870d5b99e70c1f06aff462b4839a",
            label="t-7cbc",
            taker_share=0.87, edge_cents=18.41, t_stat=0.79,
            markets=99, avg_stake_usd=4, avg_entry=0.523,
            in_scope=1.00, fills_per_day=7.0,
            assets="btc, eth 1h",
        ),
        Target(
            address="0x3c0077ed91ea7234f0ce245bbdd024630680ba3c",
            label="t-3c00",
            taker_share=0.86, edge_cents=16.63, t_stat=1.34,
            markets=19, avg_stake_usd=51, avg_entry=0.488,
            in_scope=1.00, fills_per_day=19.4,
            assets="btc, eth 1h",
        ),
        Target(
            address="0xc15fa88815941dcdb88874c8aaac2b3aba3da7d9",
            label="t-c15f",
            taker_share=0.87, edge_cents=15.97, t_stat=1.13,
            markets=53, avg_stake_usd=24, avg_entry=0.421,
            in_scope=0.68, fills_per_day=9.7,
            assets="btc, eth 1h",
        ),
        Target(
            address="0xf001248378add143949099d8b0be236d10dda1cd",
            label="t-f001",
            taker_share=1.00, edge_cents=13.80, t_stat=1.33,
            markets=13, avg_stake_usd=5, avg_entry=0.857,
            in_scope=0.76, fills_per_day=3.0,
            assets="btc, eth 1h",
        ),
        Target(
            address="0xc8116d8347ab423a40818ec2dd44634f170e8b4c",
            label="t-c811",
            taker_share=1.00, edge_cents=13.14, t_stat=2.27,
            markets=25, avg_stake_usd=5, avg_entry=0.869,
            in_scope=1.00, fills_per_day=1.3,
            assets="btc, eth 1h",
        ),
        Target(
            address="0x497bfd4a2f0008f9e0e01dcbd3a807f691482fc5",
            label="t-497b",
            taker_share=1.00, edge_cents=10.78, t_stat=0.90,
            markets=19, avg_stake_usd=1, avg_entry=0.168,
            in_scope=0.96, fills_per_day=4.0,
            assets="btc, eth 1h",
        ),
        Target(
            address="0xcc8ad3a91ee3b112211f1adca538ac96e8184425",
            label="t-cc8a",
            taker_share=1.00, edge_cents=10.54, t_stat=2.68,
            markets=25, avg_stake_usd=29, avg_entry=0.821,
            in_scope=1.00, fills_per_day=0.3,
            assets="btc, eth 1h",
        ),
        Target(
            address="0x7b729fbeee244fcd12a44875461abbaf5402dfb4",
            label="t-7b72",
            taker_share=0.98, edge_cents=9.98, t_stat=0.47,
            markets=190, avg_stake_usd=4, avg_entry=0.556,
            in_scope=1.00, fills_per_day=18.0,
            assets="btc, eth 1h",
            note="mid-price taker with a 190-market record - the shape the screen was asked for.",
        ),
        Target(
            address="0x5ecce66373f86b2b44b779c4f3adfa2456e78abd",
            label="t-5ecc",
            taker_share=0.86, edge_cents=9.04, t_stat=0.82,
            markets=195, avg_stake_usd=8, avg_entry=0.828,
            in_scope=1.00, fills_per_day=8.4,
            assets="btc, eth 1h",
            note="large sample: 195 markets.",
        ),
        Target(
            address="0x254521adbc506e70f140cae760caa7b9c4e6e5d7",
            label="t-2545",
            taker_share=1.00, edge_cents=8.76, t_stat=0.93,
            markets=35, avg_stake_usd=5, avg_entry=0.897,
            in_scope=1.00, fills_per_day=1.4,
            assets="btc, eth 1h",
        ),
        Target(
            address="0x35e7ed6cf90b5b0c338cf78d6d0dc8977fc0c415",
            label="t-35e7",
            taker_share=1.00, edge_cents=8.73, t_stat=1.50,
            markets=289, avg_stake_usd=23, avg_entry=0.928,
            in_scope=1.00, fills_per_day=19.4,
            assets="btc, eth 1h",
            note="large sample: 289 markets.",
        ),
        Target(
            address="0x9635985bfdeb2265db9d0e3649a018a87760a71f",
            label="t-9635",
            taker_share=1.00, edge_cents=8.19, t_stat=1.81,
            markets=28, avg_stake_usd=6, avg_entry=0.897,
            in_scope=0.62, fills_per_day=6.7,
            assets="btc, eth 1h",
        ),
        Target(
            address="0xe8c2d6dfbeb46e70dd08a849c65b4819f162b5fd",
            label="t-e8c2",
            taker_share=1.00, edge_cents=7.10, t_stat=2.38,
            markets=166, avg_stake_usd=17, avg_entry=0.916,
            in_scope=1.00, fills_per_day=13.7,
            assets="btc, eth 1h",
            note="large sample: 166 markets.",
        ),
        Target(
            address="0xef56de00e2da335b89e3d6407b01a12645eaedda",
            label="t-ef56",
            taker_share=1.00, edge_cents=6.95, t_stat=3.76,
            markets=81, avg_stake_usd=225, avg_entry=0.928,
            in_scope=1.00, fills_per_day=3.3,
            assets="btc, eth 1h",
        ),
        Target(
            address="0x1c7cf0523d8df1ca95661eb3135da67980828faa",
            label="t-1c7c",
            taker_share=1.00, edge_cents=6.63, t_stat=1.74,
            markets=232, avg_stake_usd=15, avg_entry=0.933,
            in_scope=0.96, fills_per_day=15.4,
            assets="btc, eth 1h",
            note="large sample: 232 markets.",
        ),
        Target(
            address="0x9eebaf2a2960369b05cb24823e65ecf243ba3dd9",
            label="t-9eeb",
            taker_share=1.00, edge_cents=6.26, t_stat=1.02,
            markets=294, avg_stake_usd=29, avg_entry=0.944,
            in_scope=1.00, fills_per_day=13.0,
            assets="btc, eth 1h",
            note="large sample: 294 markets.",
        ),
        Target(
            address="0xc4098739a4aa22e0bc8ca1891d7e9267973cc19a",
            label="t-c409",
            taker_share=0.80, edge_cents=5.82, t_stat=0.47,
            markets=51, avg_stake_usd=1, avg_entry=0.497,
            in_scope=1.00, fills_per_day=13.0,
            assets="btc, eth 1h",
        ),
        Target(
            address="0x2f99a13102d68769e2a63f42ea553d5f80ea1074",
            label="t-2f99",
            taker_share=0.97, edge_cents=5.00, t_stat=0.53,
            markets=219, avg_stake_usd=8, avg_entry=0.937,
            in_scope=1.00, fills_per_day=9.9,
            assets="btc, eth 1h",
            note="large sample: 219 markets.",
        ),
        Target(
            address="0xe208cc02257cbc5570e0ddd0a631afab1d934e40",
            label="t-e208",
            taker_share=0.80, edge_cents=4.31, t_stat=0.40,
            markets=149, avg_stake_usd=13, avg_entry=0.343,
            in_scope=0.63, fills_per_day=22.6,
            assets="btc, eth 1h",
            note="mid-price taker with a 149-market record - the shape the screen was asked for.",
        ),
        Target(
            address="0x45a085ec3afd3076af9d6feb8c3cc2a0e4fb4be5",
            label="m-45a0",
            taker_share=0.63, edge_cents=31.71, t_stat=1.34,
            markets=260, avg_stake_usd=11, avg_entry=0.678,
            in_scope=1.00, fills_per_day=16.6,
            assets="btc, eth, sol, xrp 15m",
            note="notably deep 15m record: 260 markets.",
        ),
        Target(
            address="0xa225f0c98344716610d989f7b30b31fed1a540bf",
            label="m-a225",
            taker_share=0.66, edge_cents=27.81, t_stat=1.20,
            markets=68, avg_stake_usd=22, avg_entry=0.523,
            in_scope=1.00, fills_per_day=2.6,
            assets="btc, eth, sol, xrp 15m",
        ),
        Target(
            address="0x0aefdd2365c50060a276cbd2832931d32355e9a1",
            label="m-0aef",
            taker_share=0.91, edge_cents=7.28, t_stat=1.46,
            markets=202, avg_stake_usd=89, avg_entry=0.524,
            in_scope=0.71, fills_per_day=23.3,
            assets="btc, eth, sol, xrp 15m",
            note="mid-price 15m taker over 202 markets.",
        ),
        Target(
            address="0x8614d67d229cf2cc982b31726bb8633bbe06bb9d",
            label="m-8614",
            taker_share=0.62, edge_cents=16.07, t_stat=1.41,
            markets=96, avg_stake_usd=4, avg_entry=0.671,
            in_scope=1.00, fills_per_day=6.0,
            assets="btc, eth, sol, xrp 15m",
        ),
        Target(
            address="0x8d2fdc98548c93211286c2bdf613322bfb3452f6",
            label="m-8d2f",
            taker_share=0.88, edge_cents=18.29, t_stat=1.39,
            markets=60, avg_stake_usd=2, avg_entry=0.229,
            in_scope=1.00, fills_per_day=2.3,
            assets="btc, eth, sol, xrp 15m",
        ),
        Target(
            address="0xf6ec4d8af29018a08c67fc105301e65fabbab67a",
            label="m-f6ec",
            taker_share=0.81, edge_cents=6.38, t_stat=1.46,
            markets=165, avg_stake_usd=44, avg_entry=0.617,
            in_scope=0.62, fills_per_day=19.4,
            assets="btc, eth, sol, xrp 15m",
            note="notably deep 15m record: 165 markets.",
        ),
        Target(
            address="0xa1e3067fd065e90d1844cba170290b68d591f6bc",
            label="m-a1e3",
            taker_share=0.68, edge_cents=16.02, t_stat=2.05,
            markets=58, avg_stake_usd=46, avg_entry=0.698,
            in_scope=0.95, fills_per_day=2.7,
            assets="btc, eth, sol, xrp 15m",
        ),
        Target(
            address="0xb476d52d74d0ecd55fb80f9bc96e93a267ad6eac",
            label="m-b476",
            taker_share=0.91, edge_cents=10.03, t_stat=2.33,
            markets=85, avg_stake_usd=181, avg_entry=0.868,
            in_scope=0.70, fills_per_day=8.0,
            assets="btc, eth, sol, xrp 15m",
        ),
        Target(
            address="0x384647a2e8a8b450e247d160fdc6d3fad15ce262",
            label="m-3846",
            taker_share=0.63, edge_cents=10.84, t_stat=1.85,
            markets=60, avg_stake_usd=3, avg_entry=0.543,
            in_scope=1.00, fills_per_day=1.7,
            assets="btc, eth, sol, xrp 15m",
        ),
        Target(
            address="0x5fc108a8e8621fb10bf508bf4f224f531320f591",
            label="m-5fc1",
            taker_share=1.00, edge_cents=9.63, t_stat=1.39,
            markets=66, avg_stake_usd=9, avg_entry=0.141,
            in_scope=1.00, fills_per_day=2.9,
            assets="btc, eth, sol, xrp 15m",
        ),
        Target(
            address="0x6c85ade8aed6b19783a71fa604d29dc4ac1733f4",
            label="m-6c85",
            taker_share=0.81, edge_cents=5.01, t_stat=1.74,
            markets=103, avg_stake_usd=35, avg_entry=0.517,
            in_scope=1.00, fills_per_day=13.1,
            assets="btc, eth, sol, xrp 15m",
            note="mid-price 15m taker over 103 markets.",
        ),
        Target(
            address="0x323356b56298a0bfbc46aca8eee01a436ea95225",
            label="m-3233",
            taker_share=0.74, edge_cents=8.01, t_stat=1.39,
            markets=73, avg_stake_usd=19, avg_entry=0.704,
            in_scope=1.00, fills_per_day=3.1,
            assets="btc, eth, sol, xrp 15m",
        ),
        Target(
            address="0x01bb1b121212a7165bb5badd76bec92f408733f5",
            label="m-01bb",
            taker_share=1.00, edge_cents=7.68, t_stat=1.26,
            markets=52, avg_stake_usd=3, avg_entry=0.661,
            in_scope=1.00, fills_per_day=2.9,
            assets="btc, eth, sol, xrp 15m",
        ),
        Target(
            address="0x70ba09cac52139a8a00e1d8ea78577ec86c31eca",
            label="m-70ba",
            taker_share=0.76, edge_cents=8.31, t_stat=1.10,
            markets=47, avg_stake_usd=1, avg_entry=0.726,
            in_scope=1.00, fills_per_day=1.9,
            assets="btc, eth, sol, xrp 15m",
        ),
        Target(
            address="0x14db3720c0e27112c2a5aa25ff624dfe2225d8d0",
            label="m-14db",
            taker_share=0.64, edge_cents=5.03, t_stat=1.35,
            markets=42, avg_stake_usd=1, avg_entry=0.477,
            in_scope=1.00, fills_per_day=7.6,
            assets="btc, eth, sol, xrp 15m",
        ),
    )
}

DEFAULT_TARGET = "0x8d773331e432935c7cb6c24ded4c5e1a8f35ee05"
"""Highest taker edge per share among the drift-checked survivors."""


def get(address: str) -> Target | None:
    return TARGETS.get(address.lower())
